language: csharp
solution: Giovanebribeiro.MSBuild.SCM.Tasks.sln
install:
 - nuget restore Giovanebribeiro.MSBuild.SCM.Tasks.sln
 - nuget install NUnit.Runners -OutputDirectory testrunner
 - cp testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe 
script:
 - xbuild build.proj /p:Configuration=Release /t:Compile
