language: csharp
solution: Giovanebribeiro.MSBuild.SCM.Tasks.sln
before_install:
 - sudo apt-get install nunit-console
before_script:
 - nuget restore Giovanebribeiro.MSBuild.SCM.Tasks.sln
after_script:
  - nunit-console C:\workspace\msbuildscmtasks\MSBuild.SCM.Tasks.BumpVersion.Test\bin\Release\MSBuild.SCM.Tasks.BumpVersion.Test.dll 
  - nunit-console C:\workspace\msbuildscmtasks\MSBuild.SCM.Tasks.Changelog.Test\bin\Release\MSBuild.SCM.Tasks.Changelog.Test.dll 
  - nunit-console C:\workspace\msbuildscmtasks\MSBuild.SCM.Tasks.Git.Test\bin\Release\MSBuild.SCM.Tasks.Git.Test.dll 
